version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: isort
    versions:
    - "> 4.3.21"
  - dependency-name: mypy
    versions:
    - "> 0.782"
  - dependency-name: flake8
    versions:
    - 3.8.4
    - 3.9.0
  - dependency-name: pydantic
    versions:
    - 1.7.3
    - "1.8"
  - dependency-name: pytest-mock
    versions:
    - 3.5.1
  - dependency-name: black
    versions:
    - 20.8b1
